name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Restore Astro cache
        uses: actions/cache/restore@v4
        with:
          path: node_modules/.astro
          key: ${{ runner.os }}-astro-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-astro-

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Save Astro cache
        uses: actions/cache/save@v4
        with:
          path: node_modules/.astro
          key: ${{ runner.os }}-astro-${{ github.run_id }}

      - name: Deploy
        run: aws s3 sync ./dist s3://${{ secrets.STAGING_AWS_S3_BUCKET }}/tech-docs --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.STAGING_AWS_REGION }}
