name: Deploy

on:
  push:
    branches:
      - staging

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            lfs: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Restore cache from S3
        run: |
          aws s3 cp s3://${{ secrets.STAGING_AWS_S3_BUCKET }}/cache/astro-cache.tar.gz astro-cache.tar.gz || true
          tar -xzf astro-cache.tar.gz || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.STAGING_AWS_REGION }}

      - name: Install
        run: pnpm install --prod

      - name: Build
        run: pnpm build

      - name: Save cache to S3
        run: |
          tar -czf astro-cache.tar.gz node_modules/.astro
          aws s3 cp astro-cache.tar.gz s3://${{ secrets.STAGING_AWS_S3_BUCKET }}/cache/astro-cache.tar.gz
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.STAGING_AWS_REGION }}

      - name: Deploy
        run: aws s3 sync ./dist s3://${{ secrets.STAGING_AWS_S3_BUCKET }}/tech-docs --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.STAGING_AWS_REGION }}
